### ISSUE TITLE
Today button doesn't work

### ISSUE THREAD

**Issue by ata-marzban** [AmirkabirDataMiners/ADM-dateTimePicker#101] opened 2017-07-19 08:21 UTC
Clicking the today button just refreshes the calendar and doesn't select the present day.

**Comment by arash-khajelou** [comment] 2017-07-20 15:13
the today button in every calendar module, works like that :) so this is not a bug or issue :d

**Comment by ata-marzban** [comment] 2017-07-20 19:38
Yeah you're right i noticed that later the same day.

**Comment by arash-khajelou** [comment] 2017-07-25 17:41
so you can close the issue

**Closed as completed** 2017-07-29 12:16 UTC
